---
- name: Create Drupal site dir.
  file:
    path: "{{ drupal_core_dir }}"
    state: directory
    owner: "{{ drupal_user }}"
    group: "{{ drupal_group }}"

- name: Copy Drupal makefile.
  copy: src={{ drupal_makefile_file }} dest=/tmp/drupal.make.yml
  sudo: no

- name: Build Drupal makefile.
  command: >
    {{ drush_path }} make -y /tmp/drupal.make.yml --no-gitinfofile
    chdir={{ drupal_core_dir }}
  sudo: no

- name: Copy Drupal settings.php.
  template:
    src: settings.php.j2
    dest: "{{ drupal_core_dir }}/sites/default/settings.php"
  sudo: no
