---
- name: Check Drupal bootstrap.
  command: >
    {{ drush_path }} st bootstrap
    chdir={{ drupal_core_dir }}
  register: drupal_site_installed
  failed_when: false
  changed_when: false
  sudo: no

- name: Install Drupal profile.
  command: >
    {{ drush_path }} si {{ drupal_profile }} -y
    --site-name="{{ drupal_profile_site_name }}"
    --account-name={{ drupal_profile_user }}
    --account-pass={{ drupal_profile_pass }}
    chdir={{ drupal_core_dir }}
  notify: restart webserver
  when: "'Successful' not in drupal_site_installed.stdout"
  sudo: no
