---
- name: Check Drupal setup.
  stat: path={{ drupal_core_dir }}/index.php
  register: drupal_site

- include: build.yml
  when: drupal_makefile_build and (drupal_site.stat.exists == false)

- include: install.yml
  when: drupal_profile_install

- include: secure.yml
