---
- name: check drupal bootstrap
  command: >
    {{ drush_exec }} st bootstrap
    chdir={{ drupal_core_dir }}
  register: drupal_site_installed
  failed_when: false
  changed_when: false

- name: install drupal profile
  command: >
    {{ drush_exec }} si {{ drupal_profile }} -y
    --site-name="{{ drupal_profile_site_name }}"
    --account-name={{ drupal_profile_user }}
    --account-pass={{ drupal_profile_pass }}
    chdir={{ drupal_core_dir }}
  when: "'Successful' not in drupal_site_installed.stdout"
