---
- name: Set Drupal dirs permissions.
  command: find {{ drupal_core_dir }} -type d -exec chmod 0750 {} \;
  when: drupal_site.stat.exists == false

- name: Set Drupal file permissions.
  command: find {{ drupal_core_dir }} -type f -exec chmod 0640 {} \;
  when: drupal_site.stat.exists == false

- name: Set Drupal 'default/files' permissions.
  file:
    path: "{{ drupal_core_dir }}/sites/default/files"
    state: directory
    mode: 0770

- name: Set Drupal settings.php permissions.
  file:
    path: "{{ drupal_core_dir }}/sites/default/settings.php"
    state: file
    mode: 0440

- name: Set Drupal site dir permissions.
  file:
    path: "{{ drupal_core_dir }}"
    state: directory
    owner: "{{ drupal_user }}"
    group: "{{ drupal_group }}"
    recurse: yes
